language: node_js
node_js:
  - "7"
branches:
  only:
  - master
  - develop
before_deploy: "start deploy"
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    branch: master
    tags: true
before_deploy: "finish deploy"